Updating Skyblock Joining & Leaving Logic, Fixed Location updates, Added Logging.
SkyBlock-Central/SkyBlock-Core pull request #12
Opened 2023-05-21 05:37 UTC by wiviw5

This updated code is for a new bit of logic where Detection is based on what the active scoreboard name is, rather than the old system of updating based on reading a line from the scoreboard (which broke during `SKIBLOCK`).

**How it works:**
Joining to a Hypixel lobby gives us for example `Prototype` as a new name. Telling us that the client no longer is within Skyblock.

Joining into Skyblock, we receive two Scoreboards, one named `health` and the other `SBScoreboard`, this also goes along with transferring islands, we also receive this set of packets. 

We ignore `health` as this can lead to false positives for other gamemodes (As it is a common name for scoreboard names)

Next, we check for if it contains `SBScoreboard` and if it does, then we interact with the event, and we are officially "on Skyblock"

lastly, we check for any other Scoreboard, if we do not find `SBScoreboard` but another one, we interact with the Leave Skyblock event, and are "off Skyblock"

**Currently known edge cases**
One edge case of this code is that if we go straight to limbo (skipping any hub/lobby) The "leave" code is never activated, and we continue to think we are still on Skyblock, even if we leave and go to another server without a scoreboard or to a singleplayer world without a scoreboard.

So, this would affect a very minor subset of servers/singleplayer worlds, however, can be fixed with a simple IP check for `*.hypixel.net` (Not implemented) which would then only affect people who get booted straight to limbo. **Please let me know if anyone has any solutions to this.**

**Location Changes**
Updated the location change code to the function of `onScoreboardDisplay`, as it needs to update on every single Scoreboard update currently.

**Logging Changes**
Added logging for new Location change code, along with the join/leave Skyblock code.

In the future, this should be behind a toggle for developers for simply debugging if anything goes wrong with this code.

2023-05-21 06:09 UTC, KyllianGamer commented
Looks fine for the join and leave detection, given it works ofcourse. But for the logging, wouldn't devs just register a listener themselves to get a debug message like that? And furthermore, putting the actual message between "{}" doesn't make a whole lot of sense as those are generally used to log objects. Also when using the LOGGER object, the message is already prefixed with "(skyblockcore)" (the modid), so adding the name of the mod again also does not make that much sense.

2023-05-21 06:32 UTC, wiviw5 commented
> Looks fine for the join and leave detection, given it works ofcourse.

Haha, forgot to mention, I did some basic testing with Dungeons, Skyblock hub, Personal island, Main Lobby, and Prototype lobby and it worked flawlessly for the logic on the ones I tested here. However I need a bit more testing to make sure Kuudra, Rift, Straight to limbo, and all other Skyblock islands work, but I did not have time for those today. 

>  But for the logging, wouldn't devs just register a listener themselves to get a debug message like that?

Yes, but also, if its just built in, that allows people reporting issues/developers trying to find out why their mods not working with the core mod to do it without recompiling and re-logging into Hypixel.

> And furthermore, putting the actual message between "{}" doesn't make a whole lot of sense as those are generally used to log objects.

Only did this for visibility sake temporarily while writing this. In the future, I'd like to have something more professional yes.

> Also when using the LOGGER object, the message is already prefixed with "(skyblockcore)" (the modid), so adding the name of the mod again also does not make that much sense.

It in fact did not prefix my logs with that. Examples below:
`[23:44:17] [Render thread/INFO]: [SkyblockCore] {SKYBLOCK SB "Joined SB"} SBScoreboard`
`[23:44:17] [Render thread/INFO]: [SkyblockCore] {Health Scoreboard "Ignored"} health`
`[23:44:17] [Render thread/INFO]: [SkyblockCore] {Location Changed from: null to: Your Island}`
`[23:45:26] [Render thread/INFO]: [SkyblockCore] {Other Scoreboard, "Quit SB"} Prototype`

As to why it did not. I have no clue. Wasn't due to anything special that I am aware of either in the development environment/client testing I did there. (And yes, I was hoping it would actually prefix it, but since it didn't, I made this change to be able to spot it within my logs for the time being.)

2023-05-22 16:16 UTC, AxleCat284 commented
didnt mean to even push here but 

chAnGeS

### Changes

- Not working command handling for `/sbcore dev` handler thing yeah 
- Formatting for the logs (it looks nice I was planning to make dev toggle then push but HERE WE ARE!)

2023-05-22 16:35 UTC, AxleCat284 commented
Added better formatting for logs
### Changes

- Changed all of the formatting of joining/leaving skyblock and zone changes to be a bit more simplified
- Added a dev mode (currently there is no way to toggle this, to turn this off go to `src\main\...\SkyblockCore.java\` it is currently set to `TRUE`
- @wiviw5 and I talked about adding some sort of ingame command and config, I have been working on this and the pr should come soon enough

I have verifed that I am commiting to pr/12
I have checked and tested my code and it has launched and dev mode has worked both on `TRUE` and `FALSE`

2023-05-22 19:37 UTC, wiviw5 commented
I fixed the last bit of formatting here, its of course still temporary. But now looks better for transitions between locations.

2023-05-22 20:05 UTC, AxleCat284 commented
> I fixed the last bit of formatting here, its of course still temporary. But now looks better for transitions between locations.

Thanks! I actually fixed it but when i was re-pr'ing it somehow got deleted

2023-05-22 20:06 UTC, AxleCat284 commented
If you want you can start working on the command (or anyone else) since I can probably finish the config

2023-05-22 21:29 UTC, Harry282 commented
that's crazy

2023-05-22 21:30 UTC, axlecoffee commented
> that's crazy

👍 my phone vibrated for you, good job!

2023-05-22 21:31 UTC, Harry282 commented
> 👍 my phone vibrated for you, good job!

got an email for that, good job!

2023-05-22 23:16 UTC, AxleCat284 commented
Added a config file, and formatting
## Additions
- Config creator and handler in JSON
- Added a dev toggle and location toggle
## Changes
- Merged formatting used in the last commit in this pr from @wiviw
- Changed a few logging things to include MODID

I have tested my code and it has launched with all toggles tested
I have changed where I am commiting
I have added information on how to add a config option in ModConfig.java

### TODO for this pr
- Add a command ingame to toggle
- at some point documentation...

2023-05-23 04:57 UTC, wiviw5 commented
Fixed some config file shenanigans & tested out a new command. (made sure that when checking if developer/location feedback mode was enabled was actually respected.)

### Additions

Added a local only command to do testing with, and to eventually give users feedback.

Currently looking at:
`/skyblockcore <subcommand>`

With the subcommands being:
- reload (For hot reloading of the file if manually edited.)
- nbt (Currently not implemented, for future nbt grabbing from items/entities.)
- dev (Not implemented, for future enable & disable of developer feedback logs.)
- location (Not implemented, for future enable & disable of developer feedback logs.)

### Changes

- Changed a few bits of config checking to make sure changes to the config were respected when reloaded.
- Made sure config loading & Command registration was done at the proper times in loading.

### TODO
- Better feedback to the player on the commands. (Optimally, I would like every single thing we send to the players chat window in translatable text.)
- Implementation of the commands

2023-05-23 14:38 UTC, Ascynx submitted a review, later dismissed

2023-05-23 14:38 UTC, Ascynx commented on src/main/java/io/github/skyblockcore/SkyblockCore.java
> +        File configFile = new File(FabricLoader.getInstance().getConfigDir() + File.separator + "SkyblockCoreConfig.json");
```suggestion
        File configFile = FabricLoader.getInstance().getConfigDir().resolve("SkyblockCoreConfig.json").toFile();
```

2023-05-23 14:38 UTC, Ascynx commented on build.gradle
> +	implementation 'com.google.code.gson:gson:2.8.9'
Isn't Gson already included with fabric?

2023-05-23 14:38 UTC, Ascynx commented on src/main/java/io/github/skyblockcore/SkyblockCore.java
> +        File configFile = new File(FabricLoader.getInstance().getConfigDir() + File.separator + "SkyblockCoreConfig.json");
See above comment

2023-05-23 14:38 UTC, Ascynx commented on src/main/java/io/github/skyblockcore/command/SkyblockCoreCommand.java
> +        LOGGER.info(TITLE + " This would of started/stopped showing developer location data.");
```suggestion
        LOGGER.info(TITLE + " This would have started/stopped showing developer location data.");
```

2023-05-23 14:38 UTC, Ascynx commented on src/main/java/io/github/skyblockcore/command/SkyblockCoreCommand.java
> +        LOGGER.info(TITLE + " This would of started/stopped showing developer data.");
```suggestion
        LOGGER.info(TITLE + " This would have started/stopped showing developer data.");
```

2023-05-23 14:38 UTC, Ascynx commented on src/main/java/io/github/skyblockcore/command/SkyblockCoreCommand.java
> +        LOGGER.info(TITLE + " This would of started/stopped the NBT data.");
```suggestion
        LOGGER.info(TITLE + " This would have started/stopped the NBT data.");
```

2023-05-23 14:38 UTC, Ascynx commented on src/main/java/io/github/skyblockcore/SkyblockCore.java
> +    private static final String TITLE = "[SkyblockCore]";
Logger already prefixes what is sent through it with "(skyblockcore)" I don't see the use.

2023-05-23 14:38 UTC, Ascynx commented on src/main/java/io/github/skyblockcore/mixin/PlayNetworkHandlerMixin.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(ModID);
Just call it from SkyblockCore when used, why create a new one?

2023-05-23 14:38 UTC, Ascynx commented on src/main/java/io/github/skyblockcore/mixin/PlayNetworkHandlerMixin.java
> +    private static final String TITLE = "[SkyblockCore]";
See first comment in SkyblockCore

2023-05-23 14:42 UTC, AxleCat284 commented on src/main/java/io/github/skyblockcore/SkyblockCore.java
> +    private static final String TITLE = "[SkyblockCore]";
its cooler to use []

2023-05-23 14:57 UTC, wiviw5 commented
Fixes requested by Ascynx included fixing the loggers in separate classes, some spelling, removal of GSON (provided by fabric already), and questions on logger reasoning.

2023-05-23 15:50 UTC, Harry282 commented
Why is the config instance nullable? There shouldn't have to be a null check every time we want to access the config.

2023-05-23 16:08 UTC, AxleCat284 commented
Oh that's odd, I think my IDE complained without it... but yeah you're right it shouldn't be nullable

2023-05-23 16:09 UTC, AxleCat284 commented
If you want @Harry282 you can commit a fix

2023-05-23 16:53 UTC, TGWaffles commented
Fixed the (sub-island) location listener.

It used to listen only for objective updates, but the location isn't actually an objective name - instead it's a team name.

Now we only update the location when we actually receive a team update packet from Hypixel with the location character (U+23E3) as the first character (excluding whitespace). 

Works very reliably, and updates instantly when the player location changes in scoreboard. Added bonus effect of partial location updates as Hypixel partially updates the location (but these only persist for a few milliseconds until Hypixel sends the full update).

2023-05-23 17:07 UTC, AxleCat284 commented
### Changes
- Made the TITLE string public
- Made scoreboard strings public
- Removed the private versions of ^
- Removed some random lines blankness
- Formatted a tiny bit of logging and changed a few things
### Additions
- Commands now have ingame replies (No color yet, and just basic they still dont do stuff)

### TODO
- Make commands do stuff
- Add color to commands
- change around some logging
- Fix config being nullable
- add a time calc for reloading config
- add a way to reload config
- fix all of the headaches with LOGGER sometimes showing weird stuff
- Fix issues with location

I have checked that my code works in developer launch and normal minecraft
![image](https://github.com/SkyBlock-Central/SkyBlock-Core/assets/95949634/fb891ebf-3c7d-4ef3-b51c-32125b00abb8)

2023-05-23 17:26 UTC, wiviw5 commented
Fixed up player checks.

2023-05-23 17:37 UTC, TGWaffles requested changes

2023-05-23 17:37 UTC, TGWaffles commented on src/main/java/io/github/skyblockcore/SkyblockCore.java
> +            LOGGER.info(TITLE + " Config successfully created! Welcome to SkyblockCore, a Skyblock mod designed for modern Minecraft.");
Is SkyblockCore... a mod?

2023-05-23 17:37 UTC, TGWaffles commented on src/main/java/io/github/skyblockcore/SkyblockCore.java
> +            LOGGER.info(TITLE + " Config successfully created! Welcome to SkyblockCore, a Skyblock mod designed for modern Minecraft.");
If this is just temporary for testing that's fine, maybe add a comment to specify that

2023-05-23 17:37 UTC, TGWaffles commented on src/main/java/io/github/skyblockcore/SkyblockCore.java
> +    }
Might be an idea to move this to the ModConfig class itself so we don't have to deal with file logic in the main class.

2023-05-23 17:37 UTC, TGWaffles commented on src/main/java/io/github/skyblockcore/command/SkyblockCoreCommand.java
> +        if (MinecraftClient.getInstance().player == null) return 0;
```suggestion
        if (MinecraftClient.getInstance().player == null) return 0;
```

This is good.

2023-05-23 17:37 UTC, TGWaffles commented on src/main/java/io/github/skyblockcore/mixin/PlayNetworkHandlerMixin.java
>          }
Can this not either be an else to the previous if statement, or a check after "health" with an early-return?

2023-05-23 17:57 UTC, wiviw5 commented
Changed around format of getting whether the user has joined or left Skyblock.

This removes a single string comparison now that we check for anything but specific strings associated with Skyblock.

2023-05-23 17:58 UTC, AxleCat284 commented on src/main/java/io/github/skyblockcore/SkyblockCore.java
> +            LOGGER.info(TITLE + " Config successfully created! Welcome to SkyblockCore, a Skyblock mod designed for modern Minecraft.");
What might end up happening is that itll download on start, not sure yet

2023-05-23 17:59 UTC, axlecoffee commented on src/main/java/io/github/skyblockcore/SkyblockCore.java
> +    }
I am planning on doing that

2023-05-23 19:11 UTC, AxleCat284 commented
### Additions 
- Made a new class for config stuff to remove it from the main class
- `io.github.skyblockcore.event.ConfigManager`
- Made all the commands (aside from NBT) do stuff 

### Changes
- Changed all old config uses to use the new method 
![image](https://github.com/SkyBlock-Central/SkyBlock-Core/assets/95949634/e180e636-64b6-4229-8d72-caf3ce4a8edf)

### Known issues
- I somehow caused see image

2023-05-23 21:29 UTC, AxleCat284 commented
### Additions 
- Log filtering 
- log filter toggle command
- log filter config lines
- test command!
- cute catboys

### Changes
- Removed the femboys from an old update as it was ruining the motivation of the team 

I have tested this and it has launched and built in dev and in minecraft 

### TODO
- Fix config not allowing new code to be printed without hard reset 
- colors 🌈 🏳️‍🌈 🏳️‍⚧️ 👑 💅 💅 💅 💅 👄 💋 💄

2023-05-26 15:58 UTC, TGWaffles commented
Is this ready for reviews?

2023-05-26 16:16 UTC, axlecoffee commented
> Is this ready for reviews?

You have pending changes iirc

2023-05-26 16:17 UTC, AxleCat284 approved these changes

2023-05-26 19:54 UTC, TGWaffles requested changes, later dismissed

2023-05-26 19:54 UTC, TGWaffles commented on src/main/java/io/github/skyblockcore/SkyblockCore.java
> +        });
Putting this in client tick seems like a REALLY bad idea. Would this not be better eg in tooltip event so it's only triggered in a gui and when we're hovering over an item? 

Could possibly also just mixin over the method that colours the focused slot?

2023-05-29 01:02 UTC, Nahydrin commented on src/main/java/io/github/skyblockcore/SkyblockCore.java
> +        });
This will be opened as an issue.

2023-05-29 01:05 UTC, Nahydrin approved these changes

2023-05-29 01:05 UTC, merged